### PR TITLE
Add systemd for RHEL 7

### PR DESCRIPTION
**Pull request by ngourley**

### CODE REVIEW

**Comment by rayrod2030** [comment]
Hi @ngourley please merge latest into your PR and fix conflicts.  Thanks.

**Comment by ngourley** [comment]
@rayrod2030 I have merged latest and fixed conflicts. Let me know if anything else needs to be done, thanks!

**Comment by jmauro** [comment]
Hey,

@ngourley just to let you know that I have also created a PR for Rhel 7 by using `poise-service`, it might be a bit easier to maintain since all the magic is handled by poise.

Let me know what you think of it.

Regards,
JM

**Comment by ngourley** [comment]
@jmauro I haven't used poise-service before, but it appears to provide the required abstraction to the service provider. As long as the cookbook provides support for centos/rhel7 I'm down.

@rayrod2030 Could we get a merge on the branch by @jmauro? I will close my pull request afterward.

**Comment by rveznaver** [comment]
Merged #40, please open a new pull request if you have changes other than for systemd. Thanks!

**Pull request closed without merging**
