### PR TITLE
Global refactor for Marathon 0.11.0 and mesos cookbook standard sync

### PR DESCRIPTION
**Pull request by rveznaver**
Hi,
This is a similar refactor to the one I've done for the mesos cookbook a while back and tries to align the two. There is still Debian and systemd support I would like to add. Please note that I have removed the old Ubuntu version since it does not have Java 8 in the repos (new Marathon dependency).
Tell me what you think!

Thanks,
Robert

### CODE REVIEW

**Comment by avinashkolluru** [comment]
@rveznaver When can we expect the new version of this cookbook with all these changes??

**Comment by rveznaver** [comment]
Hi @avinashkolluru, I'm not the maintainer, so I cannot answer that, sorry.

**Comment by rayrod2030** [comment]
This is great.  Thanks so much for this Robert!

**Comment by avinashkolluru** [comment]
@rayrod2030 Any update on when a new version of this cookbook will be available with support for 0.11.0?

**Pull request merged**
