### PR TITLE
re-PR due to delete of mdsol/marathon_cookbook develop branch.

### PR DESCRIPTION
**Pull request by elijah**
re-PR due to delete of mdsol/marathon_cookbook develop branch.

### CODE REVIEW

**Comment by rveznaver** [comment]
Please rebase on latest master, thanks.

**Comment by elijah** [comment]
I have done so.  Please merge, so that we're not stepping on each other's
toes with things like the .travis.yml fix.

thanks!

--e

**Comment by elijah** [comment]
It should be possible to swap back to using poise_service -- I just haven't gotten there yet.   Don't know how to get the right service files (upstart config vs. systemd marathon.service) to only provision on the proper platforms, and I'd want to do that.  I guess poise_service probably has a flag for that, need to go figure it out.

**Comment by rveznaver** [comment]
Hi @elijah,

I'm sorry, but it seems to me that this pull request does not fix anything. In addition, with the removal of ```poise_service``` we would be effectively removing support for several distributions that worked well before.
As for your issue with Ubuntu 16.04, I have added a test for it in https://github.com/mdsol/marathon_cookbook/tree/xenial. The only difference from the main branch is the fact that I had to add a workaround for the mesosphere repo, and have left everything else the same. When I run a ```kitchen converge ubuntu-1604``` the box pops up with both Mesos and Marathon configured as systemd services, therefore as far as I can tell, this is not an issue as it works as expected on a clean Ubuntu 16.04 box.
If you still think there is a bug in the cookbook, please write a test that shows the bug as it is extremely difficult to debug without being able to reproduce it.

Thanks.

**Comment by elijah** [comment]
I'll certainly pull the current master and try again.  ;-)  I was stumbling over the odd copy that was on the supermarket -- maybe all my problems just went away.

best,

--e

**Pull request closed without merging**
