### PR TITLE
Remove comma from zk join path

### PR DESCRIPTION
**Pull request by ronlipke**
Was creating incorrect zk url by adding a comma between the port number and path.

### CODE REVIEW

**Comment by rayrod2030** [comment]
@ronlipke Official Marathon docs call for the following

`
--master (Required): The URL of the Mesos master. The format is a comma-delimited list of of hosts like zk://host1:port,host2:port/mesos. If using ZooKeeper, pay particular attention to the leading zk:// and trailing /mesos! If not using ZooKeeper, standard URLs like http://localhost are also acceptable.
`

So I believe the format is correct as is.

**Comment by ronlipke** [comment]
@rayrod2030 Thanks for the docs info.  The issue I was having only shows up when using a single zk server, so the resulting url has a comma between the port and `/mesos` zk path which is incorrect syntax.  Might be an edge case, but I'll add a conditional to check for a single zk server before performing the join.  
As soon as I get some time :)

**Comment by rayrod2030** [comment]
@ronlipke I'm pretty sure that doing a join(',') on a single element list in ruby will not append the trailing character passed to the join method.

running:

```ruby
zklist = ["172.30.9.181:2181"]
puts "--zk zk://#{zklist.join(',')}/mesos"
```

results in this output:

```
--zk zk://172.30.9.181:2181/mesos
```

Are you seeing different behavior?

**Comment by ronlipke** [comment]
Not sure what happened, but I can't recreate this.  Maybe I used an attribute incorrectly or had it set wrong.  Oh well, sorry for the bother.

**Pull request closed without merging**
